# Generated by Django 3.1.7 on 2021-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'нига', 'verbose_name_plural': 'ниги'},
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
