# Generated by Django 3.1.7 on 2021-03-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_testtale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTale',
        ),
    ]
