# Generated by Django 3.1.7 on 2021-03-25 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0023_auto_20210325_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='TestTale',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.AlterUniqueTogether(
            name='likebookuser',
            unique_together={('user', 'tmp_book')},
        ),
        migrations.RemoveField(
            model_name='likebookuser',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
